const data = [
  {
    name: "Perle",
    distance: 1,
    price: 1,
    veggie: 3,
    adress: "Spitalerstraße 22, 20095 Hamburg",
    category: "all",
  },
  {
    name: "Europapassagen",
    distance: 1,
    price: 2,
    veggie: 3,
    adress: "Ballindamm 40 EG2, 20095 Hamburg",
    category: "all",
  },
  {
    name: "Max & Consorten",
    distance: 3,
    price: 1,
    veggie: 2,
    adress: "Spadenteich 1, 20099 Hamburg",
    category: "homemade",
  },
  {
    name: "Luigi's",
    distance: 3,
    price: 2,
    veggie: 3,
    adress: "Ditmar-Koel-Straße 21, 20459 Hamburg",
    category: "pizzapasta",
  },
  {
    name: "Bella Italia",
    distance: 2,
    price: 1,
    veggie: 2,
    adress: "Brandstwiete 58, 20457 Hamburg",
    category: "pizzapasta",
  },
  {
    name: "Restaurant Kabul",
    distance: 3,
    price: 1,
    veggie: 2,
    adress: "Steindamm 53, 20099 Hamburg",
    category: "other",
  },
  {
    name: "Goot",
    distance: 2,
    price: 3,
    veggie: 1,
    adress: "Depenau 10, 20095 Hamburg",
    category: "homemade",
  },
  {
    name: "O-ren Ishii",
    distance: 2,
    price: 3,
    veggie: 3,
    adress: "Kleine Reichenstraße 18, 20457 Hamburg",
    category: "asia",
  },
  {
    name: "Better Burger Company",
    distance: 1,
    price: 2,
    veggie: 3,
    adress: "Rosenstraße Ecke, Gertrudenkirchhof, 20095 Hamburg",
    category: "burger",
  },
  {
    name: "Bucks Burger",
    distance: 2,
    price: 2,
    veggie: 3,
    adress: "Kurze Mühren 13, 20095 Hamburg",
    category: "burger",
  },
  {
    name: "Mr. Cheng",
    distance: 2,
    price: 3,
    veggie: 3,
    adress: "Speersort 1, 20095 Hamburg",
    category: "asia",
  },
  {
    name: "Franco Rathauspassage",
    distance: 2,
    price: 2,
    veggie: 3,
    adress: "Rathausmarkt 7, 20095 Hamburg",
    category: "pizzapasta",
  },
];

export { data };
